name: ci
on: 
  push:
    # paths:
    #   - '**'                 # Monitor all files in the repository
    #   - '!.github/workflows/**'
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: setup Node.job
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: 'frontend/package-lock.json'

      - name: install npm package
        run: npm install --force
        working-directory: frontend

      - name: run linter
        run: npm run lint
        working-directory: frontend
      
      - name: run test
        run: npm run test
        working-directory: frontend

      - name: docker setup login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/gocart-fe:latest

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: 'backend/go.sum'

      - name: run Go formater
        run: go fmt
        working-directory: backend

      - name: Run Go vet
        run: go vet
        working-directory: backend
      
      - name: run test
        run: go test
        working-directory: backend

      - name: docker setup login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/gocart-be:latest

  deploy:
    needs: [frontend, backend]
    uses: ./.github/workflows/cd.yml
    secrets: inherit
